apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-app-deployment
  namespace: argocd-poc
  labels:
    appname: server-app
spec:
  replicas: 1
  selector:
    matchLabels:
      appname: server-app
  template:
    metadata:
      labels:
        appname: server-app
    spec:
      containers:
      - name: server-app
        image: ghcr.io/michalmorus/argocd-poc-sys-api:v1.2.0
        ports:
        - containerPort: 8080
