apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: server-app-ingress
  namespace: argocd-poc
  labels:
    appname: server-app
spec:
  routes:
  - kind: Rule
    match: Path(`/server`)
    services:
      - kind: Service
        name: server-app-service
        port: 80