apiVersion: v1
kind: Service
metadata:
  name: service-app-service
  namespace: argocd-poc
  labels:
    appname: service-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    appname: service-app